# -*- coding: utf-8 -*-
"""StockForecast

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/16-zt81QeXinUxn6aRQ5mqmaKtWT141lu
"""

#!pip install quandl
!pip install numpy

import quandl # stock info
import numpy as np # matrix math
from sklearn.linear_model import LinearRegression # predict future points
from sklearn.svm import SVR 
from sklearn.model_selection import train_test_split # splits data testing and training

df = quandl.get("WIKI/FB")
df

df = df[['Close']]
df

forecast_out = 30
df['Prediction'] = df[['Close']].shift(-forecast_out)
df

X = np.array(df.drop(["Prediction"], 1)) 
X = X[:-forecast_out]
X

y = np.array(df["Prediction"])
y = y[:-forecast_out]
y

x_train, x_test, y_train, y_test = train_test_split(X, y, test_size = 0.2)

svr_rbf = SVR(kernel = "rbf", C = 1e3, gamma = 0.1)
svr_rbf.fit(x_train, y_train)

svm_confidence = svr_rbf.score(x_test, y_test)
svm_confidence